import type { Theme } from "./types";

export const THEMES: Theme[] = [
  {
    id: "cero",
    name: "Cero",
    description: "Default dark theme",
    colors: {
      background: "#0D0D12",
      surface: "#1A1A24",
      primary: "#56D6C2",
      selection: "#89B4FA",
      text: "#E1E1E1",
      textMuted: "#6C7086",
      textOnSelection: "#11111B",
      border: "#56D6C2",
      success: "#82E0AA",
      error: "#E74C5E",
      info: "#56D6C2",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    description: "Warm creamy dark theme",
    colors: {
      background: "#11111B",
      surface: "#1E1E2E",
      primary: "#CBA6F7",
      selection: "#89B4FA",
      text: "#CDD6F4",
      textMuted: "#6C7086",
      textOnSelection: "#11111B",
      border: "#CBA6F7",
      success: "#A6E3A1",
      error: "#F38BA8",
      info: "#89B4FA",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "Classic dark purple theme",
    colors: {
      background: "#282A36",
      surface: "#3A3C4E",
      primary: "#BD93F9",
      selection: "#6272A4",
      text: "#F8F8F2",
      textMuted: "#6272A4",
      textOnSelection: "#F8F8F2",
      border: "#BD93F9",
      success: "#50FA7B",
      error: "#FF5555",
      info: "#8BE9FD",
    },
  },
  {
    id: "nord",
    name: "Nord",
    description: "Arctic blue theme",
    colors: {
      background: "#2E3440",
      surface: "#3B4252",
      primary: "#88C0D0",
      selection: "#5E81AC",
      text: "#ECEFF4",
      textMuted: "#7B88A1",
      textOnSelection: "#ECEFF4",
      border: "#88C0D0",
      success: "#A3BE8C",
      error: "#BF616A",
      info: "#81A1C1",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "Deep blue night theme",
    colors: {
      background: "#1A1B26",
      surface: "#24283B",
      primary: "#7AA2F7",
      selection: "#565F89",
      text: "#A9B1D6",
      textMuted: "#565F89",
      textOnSelection: "#1A1B26",
      border: "#7AA2F7",
      success: "#73DACA",
      error: "#F7768E",
      info: "#7DCFFF",
    },
  },
  {
    id: "synthwave",
    name: "Synthwave",
    description: "Retro neon theme",
    colors: {
      background: "#2B213A",
      surface: "#3A2D54",
      primary: "#FF7EDB",
      selection: "#B388FF",
      text: "#E0E0FF",
      textMuted: "#8075A8",
      textOnSelection: "#1A1128",
      border: "#FF7EDB",
      success: "#00FF9F",
      error: "#FF3355",
      info: "#36F9F6",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    description: "Vibrant code theme",
    colors: {
      background: "#272822",
      surface: "#383830",
      primary: "#A6E22E",
      selection: "#75715E",
      text: "#F8F8F2",
      textMuted: "#75715E",
      textOnSelection: "#F8F8F2",
      border: "#A6E22E",
      success: "#A6E22E",
      error: "#F92672",
      info: "#66D9EF",
    },
  },
  {
    id: "gruvbox",
    name: "Gruvbox Dark",
    description: "Warm retro dark theme",
    colors: {
      background: "#282828",
      surface: "#3C3836",
      primary: "#D79921",
      selection: "#504945",
      text: "#EBDBB2",
      textMuted: "#7C6F64",
      textOnSelection: "#EBDBB2",
      border: "#D79921",
      success: "#98971A",
      error: "#CC241D",
      info: "#458588",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    description: "Popular code theme",
    colors: {
      background: "#282C34",
      surface: "#353B45",
      primary: "#61AFEF",
      selection: "#3E4452",
      text: "#ABB2BF",
      textMuted: "#5C6370",
      textOnSelection: "#ABB2BF",
      border: "#61AFEF",
      success: "#98C379",
      error: "#E06C75",
      info: "#56B6C2",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    description: "Scientific dark theme",
    colors: {
      background: "#002B36",
      surface: "#073642",
      primary: "#268BD2",
      selection: "#586E75",
      text: "#839496",
      textMuted: "#657B83",
      textOnSelection: "#FDF6E3",
      border: "#268BD2",
      success: "#859900",
      error: "#DC322F",
      info: "#2AA198",
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine",
    description: "Soft pine theme",
    colors: {
      background: "#191724",
      surface: "#2A273F",
      primary: "#EBBCBA",
      selection: "#403D52",
      text: "#E0DEF4",
      textMuted: "#6E6A86",
      textOnSelection: "#E0DEF4",
      border: "#EBBCBA",
      success: "#9CCFD8",
      error: "#EB6F92",
      info: "#31748F",
    },
  },
{
    id: "ayu-mirage",
    name: "Ayu Mirage",
    description: "Warm dusk orange theme",
    colors: {
      background: "#1F2430",
      surface: "#2D3340",
      primary: "#FFD580",
      selection: "#5C6773",
      text: "#D4D6D9",
      textMuted: "#6C7680",
      textOnSelection: "#1F2430",
      border: "#FFD580",
      success: "#A6CC70",
      error: "#F28779",
      info: "#6DCBF2",
    },
  },
  {
    id: "everforest",
    name: "Everforest",
    description: "Soft green nature theme",
    colors: {
      background: "#2D3A2E",
      surface: "#3D4A3E",
      primary: "#A7C080",
      selection: "#4F5F4F",
      text: "#D3C6AA",
      textMuted: "#778A77",
      textOnSelection: "#2D3A2E",
      border: "#A7C080",
      success: "#A7C080",
      error: "#E67E80",
      info: "#7FBBB3",
    },
  },
  {
    id: "kanagawa",
    name: "Kanagawa",
    description: "Japanese ink wash theme",
    colors: {
      background: "#1F1F28",
      surface: "#2A2A37",
      primary: "#E6C384",
      selection: "#363646",
      text: "#DCD7BA",
      textMuted: "#6F6F7F",
      textOnSelection: "#1F1F28",
      border: "#E6C384",
      success: "#76946A",
      error: "#C34043",
      info: "#7FB4CA",
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "High-contrast neon theme",
    colors: {
      background: "#0A0A0F",
      surface: "#1A1A2E",
      primary: "#FF00FF",
      selection: "#2D1B69",
      text: "#E0E0FF",
      textMuted: "#6B5B8A",
      textOnSelection: "#E0E0FF",
      border: "#FF00FF",
      success: "#00FF41",
      error: "#FF0044",
      info: "#00E5FF",
    },
  },
  {
    id: "terracotta",
    name: "Terracotta",
    description: "Warm clay earth theme",
    colors: {
      background: "#2C1E16",
      surface: "#3E2C22",
      primary: "#E76F51",
      selection: "#5A3E30",
      text: "#EAD7C3",
      textMuted: "#8B6F5E",
      textOnSelection: "#EAD7C3",
      border: "#E76F51",
      success: "#6A994E",
      error: "#BC4749",
      info: "#588B8B",
    },
  },
  {
    id: "oceanic",
    name: "Oceanic",
    description: "Deep blue aquatic theme",
    colors: {
      background: "#0A1628",
      surface: "#112640",
      primary: "#48CAE4",
      selection: "#1E4060",
      text: "#CAF0F8",
      textMuted: "#5487A0",
      textOnSelection: "#0A1628",
      border: "#48CAE4",
      success: "#2DC653",
      error: "#D90429",
      info: "#90E0EF",
    },
  },
  {
    id: "midnight-eclipse",
    name: "Midnight Eclipse",
    description: "Ultra-dark periwinkle theme",
    colors: {
      background: "#0A0A0F",
      surface: "#14141E",
      primary: "#7C83FF",
      selection: "#1E1E32",
      text: "#C8C8E0",
      textMuted: "#50506E",
      textOnSelection: "#C8C8E0",
      border: "#7C83FF",
      success: "#5EE2A0",
      error: "#FF6B6B",
      info: "#64DFDF",
    },
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Northern lights purple-green theme",
    colors: {
      background: "#0A0E1A",
      surface: "#162035",
      primary: "#B794F4",
      selection: "#253552",
      text: "#E2E8F0",
      textMuted: "#6B7B9A",
      textOnSelection: "#E2E8F0",
      border: "#B794F4",
      success: "#6EE7B7",
      error: "#FC8181",
      info: "#63B3ED",
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    description: "Familiar GitHub dimmed theme",
    colors: {
      background: "#0D1117",
      surface: "#161B22",
      primary: "#58A6FF",
      selection: "#1F3757",
      text: "#C9D1D9",
      textMuted: "#6E7681",
      textOnSelection: "#C9D1D9",
      border: "#30363D",
      success: "#3FB950",
      error: "#F85149",
      info: "#58A6FF",
    },
  },
  {
    id: "ayu-dark",
    name: "Ayu Dark",
    description: "True dark with warm orange accents",
    colors: {
      background: "#0B0E14",
      surface: "#1A1F29",
      primary: "#FFA759",
      selection: "#2D3640",
      text: "#BFBDB6",
      textMuted: "#5C6166",
      textOnSelection: "#0B0E14",
      border: "#FFA759",
      success: "#8FAA54",
      error: "#E65050",
      info: "#5CC5E8",
    },
  },
];