import type { Theme } from "./types";

// Color values for the built-in themes are sourced from opencode's theme
// definitions (https://github.com/sst/opencode/tree/dev/packages/tui/src/theme/assets),
// which curate accurate, verified palettes for each upstream project.
// `primary` doubles as the border/signature color and `selection` is the
// solid-fill highlight color for selected list rows.
export const THEMES: Theme[] = [
  {
    id: "cero",
    name: "Cero",
    description: "Default dark theme",
    colors: {
      background: "#0D0D12",
      surface: "#1A1A24",
      primary: "#56D6C2",
      selection: "#89B4FA",
      text: "#E1E1E1",
      textMuted: "#6C7086",
      textOnSelection: "#11111B",
      border: "#56D6C2",
      success: "#82E0AA",
      error: "#E74C5E",
      info: "#56D6C2",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    description: "Soothing pastel dark theme",
    colors: {
      background: "#1E1E2E",
      surface: "#181825",
      primary: "#89B4FA",
      selection: "#CBA6F7",
      text: "#CDD6F4",
      textMuted: "#9399B2",
      textOnSelection: "#1E1E2E",
      border: "#89B4FA",
      success: "#A6E3A1",
      error: "#F38BA8",
      info: "#94E2D5",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "Classic dark purple theme",
    colors: {
      background: "#282A36",
      surface: "#21222C",
      primary: "#BD93F9",
      selection: "#FF79C6",
      text: "#F8F8F2",
      textMuted: "#6272A4",
      textOnSelection: "#282A36",
      border: "#BD93F9",
      success: "#50FA7B",
      error: "#FF5555",
      info: "#FFB86C",
    },
  },
  {
    id: "nord",
    name: "Nord",
    description: "Arctic blue theme",
    colors: {
      background: "#2E3440",
      surface: "#3B4252",
      primary: "#88C0D0",
      selection: "#81A1C1",
      text: "#ECEFF4",
      textMuted: "#8B95A7",
      textOnSelection: "#2E3440",
      border: "#88C0D0",
      success: "#A3BE8C",
      error: "#BF616A",
      info: "#88C0D0",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "Deep blue night theme",
    colors: {
      background: "#1A1B26",
      surface: "#1E2030",
      primary: "#82AAFF",
      selection: "#C099FF",
      text: "#C8D3F5",
      textMuted: "#828BB8",
      textOnSelection: "#1A1B26",
      border: "#82AAFF",
      success: "#C3E88D",
      error: "#FF757F",
      info: "#82AAFF",
    },
  },
  {
    id: "gruvbox",
    name: "Gruvbox Dark",
    description: "Warm retro dark theme",
    colors: {
      background: "#282828",
      surface: "#3C3836",
      primary: "#83A598",
      selection: "#D3869B",
      text: "#EBDBB2",
      textMuted: "#928374",
      textOnSelection: "#282828",
      border: "#83A598",
      success: "#B8BB26",
      error: "#FB4934",
      info: "#FABD2F",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    description: "Vibrant classic code theme",
    colors: {
      background: "#272822",
      surface: "#1E1F1C",
      primary: "#66D9EF",
      selection: "#AE81FF",
      text: "#F8F8F2",
      textMuted: "#75715E",
      textOnSelection: "#272822",
      border: "#66D9EF",
      success: "#A6E22E",
      error: "#F92672",
      info: "#FD971F",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    description: "Popular editor theme",
    colors: {
      background: "#282C34",
      surface: "#21252B",
      primary: "#61AFEF",
      selection: "#C678DD",
      text: "#ABB2BF",
      textMuted: "#5C6370",
      textOnSelection: "#282C34",
      border: "#61AFEF",
      success: "#98C379",
      error: "#E06C75",
      info: "#D19A66",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    description: "Scientific low-contrast theme",
    colors: {
      background: "#002B36",
      surface: "#073642",
      primary: "#268BD2",
      selection: "#6C71C4",
      text: "#839496",
      textMuted: "#586E75",
      textOnSelection: "#002B36",
      border: "#268BD2",
      success: "#859900",
      error: "#DC322F",
      info: "#CB4B16",
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine",
    description: "Soft muted pine theme",
    colors: {
      background: "#191724",
      surface: "#1F1D2E",
      primary: "#9CCFD8",
      selection: "#C4A7E7",
      text: "#E0DEF4",
      textMuted: "#6E6A86",
      textOnSelection: "#191724",
      border: "#9CCFD8",
      success: "#31748F",
      error: "#EB6F92",
      info: "#9CCFD8",
    },
  },
  {
    id: "everforest",
    name: "Everforest",
    description: "Soft green nature theme",
    colors: {
      background: "#2D353B",
      surface: "#333C43",
      primary: "#A7C080",
      selection: "#7FBBB3",
      text: "#D3C6AA",
      textMuted: "#7A8478",
      textOnSelection: "#2D353B",
      border: "#A7C080",
      success: "#A7C080",
      error: "#E67E80",
      info: "#83C092",
    },
  },
  {
    id: "kanagawa",
    name: "Kanagawa",
    description: "Japanese ink wash theme",
    colors: {
      background: "#1F1F28",
      surface: "#2A2A37",
      primary: "#7E9CD8",
      selection: "#957FB8",
      text: "#DCD7BA",
      textMuted: "#727169",
      textOnSelection: "#1F1F28",
      border: "#7E9CD8",
      success: "#98BB6C",
      error: "#E82424",
      info: "#76946A",
    },
  },
  {
    id: "ayu-dark",
    name: "Ayu Dark",
    description: "True dark with warm accents",
    colors: {
      background: "#0B0E14",
      surface: "#0F131A",
      primary: "#59C2FF",
      selection: "#D2A6FF",
      text: "#BFBDB6",
      textMuted: "#565B66",
      textOnSelection: "#0B0E14",
      border: "#59C2FF",
      success: "#7FD962",
      error: "#D95757",
      info: "#39BAE6",
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    description: "Familiar GitHub dimmed theme",
    colors: {
      background: "#0D1117",
      surface: "#010409",
      primary: "#58A6FF",
      selection: "#BC8CFF",
      text: "#C9D1D9",
      textMuted: "#8B949E",
      textOnSelection: "#0D1117",
      border: "#58A6FF",
      success: "#3FB950",
      error: "#F85149",
      info: "#D29922",
    },
  },
  {
    id: "synthwave",
    name: "Synthwave '84",
    description: "Retro neon outrun theme",
    colors: {
      background: "#262335",
      surface: "#1E1A29",
      primary: "#36F9F6",
      selection: "#FF7EDB",
      text: "#FFFFFF",
      textMuted: "#848BBD",
      textOnSelection: "#262335",
      border: "#36F9F6",
      success: "#72F1B8",
      error: "#FE4450",
      info: "#FF8B39",
    },
  },
  {
    id: "matrix",
    name: "Matrix",
    description: "High-contrast hacker green theme",
    colors: {
      background: "#0A0E0A",
      surface: "#0E130D",
      primary: "#2EFF6A",
      selection: "#00EFFF",
      text: "#62FF94",
      textMuted: "#8CA391",
      textOnSelection: "#0A0E0A",
      border: "#2EFF6A",
      success: "#62FF94",
      error: "#FF4B4B",
      info: "#30B3FF",
    },
  },
];
